# Generated by Django 4.2.4 on 2023-09-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='genre',
            field=models.CharField(choices=[('education', 'Education'), ('movie', 'Movie'), ('politics', 'Politics'), ('others', 'Others')], default='education', max_length=20),
        ),
    ]
